//
//  TimeZone+Ext.swift
//	IBKit
//
//	Copyright (c) 2016-2023 Sten Soosaar
//
//	Permission is hereby granted, free of charge, to any person obtaining a copy
//	of this software and associated documentation files (the "Software"), to deal
//	in the Software without restriction, including without limitation the rights
//	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//	copies of the Software, and to permit persons to whom the Software is
//	furnished to do so, subject to the following conditions:
//
//	The above copyright notice and this permission notice shall be included in all
//	copies or substantial portions of the Software.
//
//	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//	SOFTWARE.
//


import Foundation


public extension TimeZone {
	
	init?(deprecatedName name:String) {
		
		switch name {
		case "Africa/Addis_Ababa":					self.init(identifier: "Africa/Nairobi")
		case "Africa/Asmara":	 					self.init(identifier: "Africa/Nairobi")
		case "Africa/Asmera":	 					self.init(identifier: "Africa/Nairobi")
		case "Africa/Bamako":	 					self.init(identifier: "Africa/Abidjan")
		case "Africa/Bangui":	 					self.init(identifier: "Africa/Lagos")
		case "Africa/Banjul":	 					self.init(identifier: "Africa/Abidjan")
		case "Africa/Blantyre":	 					self.init(identifier: "Africa/Maputo")
		case "Africa/Brazzaville":					self.init(identifier: "Africa/Lagos")
		case "Africa/Bujumbura":					self.init(identifier: "Africa/Maputo")
		case "Africa/Conakry":	 					self.init(identifier: "Africa/Abidjan")
		case "Africa/Dakar": 						self.init(identifier: "Africa/Abidjan")
		case "Africa/Dar_es_Salaam": 				self.init(identifier: "Africa/Nairobi")
		case "Africa/Djibouti": 					self.init(identifier: "Africa/Nairobi")
		case "Africa/Douala": 						self.init(identifier: "Africa/Lagos")
		case "Africa/Freetown": 					self.init(identifier: "Africa/Abidjan")
		case "Africa/Gaborone": 					self.init(identifier: "Africa/Maputo")
		case "Africa/Harare":						self.init(identifier: "Africa/Maputo")
		case "Africa/Kampala":						self.init(identifier: "Africa/Nairobi")
		case "Africa/Kigali":						self.init(identifier: "Africa/Maputo")
		case "Africa/Kinshasa":						self.init(identifier: "Africa/Lagos")
		case "Africa/Libreville":					self.init(identifier: "Africa/Lagos")
		case "Africa/Lome":							self.init(identifier: "Africa/Abidjan")
		case "Africa/Luanda":						self.init(identifier: "Africa/Lagos")
		case "Africa/Lubumbashi":					self.init(identifier: "Africa/Maputo")
		case "Africa/Lusaka":						self.init(identifier: "Africa/Maputo")
		case "Africa/Malabo":						self.init(identifier: "Africa/Lagos")
		case "Africa/Maseru":						self.init(identifier: "Africa/Johannesburg")
		case "Africa/Mbabane":						self.init(identifier: "Africa/Johannesburg")
		case "Africa/Mogadishu":					self.init(identifier: "Africa/Nairobi")
		case "Africa/Niamey":						self.init(identifier: "Africa/Lagos")
		case "Africa/Nouakchott":					self.init(identifier: "Africa/Abidjan")
		case "Africa/Ouagadougou":					self.init(identifier: "Africa/Abidjan")
		case "Africa/Porto-Novo":					self.init(identifier: "Africa/Lagos")
		case "Africa/Timbuktu":						self.init(identifier: "Africa/Abidjan")
		case "America/Anguilla":					self.init(identifier: "America/Port_of_Spain")
		case "America/Antigua": 					self.init(identifier: "America/Port_of_Spain")
		case "America/Argentina/ComodRivadavia":   	self.init(identifier: "America/Argentina/Catamarca")
		case "America/Aruba":						self.init(identifier: "America/Curacao")
		case "America/Atka":						self.init(identifier: "America/Adak")
		case "America/Buenos_Aires":	 			self.init(identifier: "America/Argentina/Buenos_Aires")
		case "America/Catamarca":				 	self.init(identifier: "America/Argentina/Catamarca")
		case "America/Cayman":					 	self.init(identifier: "America/Panama")
		case "America/Coral_Harbour":				self.init(identifier: "America/Atikokan")
		case "America/Cordoba":				 		self.init(identifier: "America/Argentina/Cordoba")
		case "America/Dominica":					self.init(identifier: "America/Port_of_Spain")
		case "America/Ensenada":					self.init(identifier: "America/Tijuana")
		case "America/Fort_Wayne":					self.init(identifier: "America/Indiana/Indianapolis")
		case "America/Godthab":						self.init(identifier: "America/Nuuk")
		case "America/Grenada":						self.init(identifier: "America/Port_of_Spain")
		case "America/Guadeloupe":					self.init(identifier: "America/Port_of_Spain")
		case "America/Indianapolis":				self.init(identifier: "America/Indiana/Indianapolis")
		case "America/Jujuy":						self.init(identifier: "America/Argentina/Jujuy")
		case "America/Knox_IN":				 		self.init(identifier: "America/Indiana/Knox")
		case "America/Kralendijk":					self.init(identifier: "America/Curacao")
		case "America/Louisville":					self.init(identifier: "America/Kentucky/Louisville")
		case "America/Lower_Princes":			 	self.init(identifier: "America/Curacao")
		case "America/Marigot": 		 			self.init(identifier: "America/Port_of_Spain")
		case "America/Mendoza": 		 			self.init(identifier: "America/Argentina/Mendoza")
		case "America/Montreal":			 		self.init(identifier: "America/Toronto")
		case "America/Montserrat":			 		self.init(identifier: "America/Port_of_Spain")
		case "America/Porto_Acre":			 		self.init(identifier: "America/Rio_Branco")
		case "America/Punta_Arenas":				self.init(identifier: "Magallanes Region")
		case "America/Rosario":			 			self.init(identifier: "America/Argentina/Cordoba")
		case "America/Santa_Isabel":			 	self.init(identifier: "America/Tijuana")
		case "America/Shiprock":			 		self.init(identifier: "America/Denver")
		case "America/St_Barthelemy":			 	self.init(identifier: "America/Port_of_Spain")
		case "America/St_Kitts":				 	self.init(identifier: "America/Port_of_Spain")
		case "America/St_Lucia":			 		self.init(identifier: "America/Port_of_Spain")
		case "America/St_Thomas":			 		self.init(identifier: "America/Port_of_Spain")
		case "America/St_Vincent":			 		self.init(identifier: "America/Port_of_Spain")
		case "America/Tortola":			 			self.init(identifier: "America/Port_of_Spain")
		case "America/Virgin":			 			self.init(identifier: "America/Port_of_Spain")
		case "Antarctica/McMurdo":			 		self.init(identifier: "Pacific/Auckland")
		case "Antarctica/South_Pole": 		 		self.init(identifier: "Pacific/Auckland")
		case "Arctic/Longyearbyen":	 				self.init(identifier: "Europe/Oslo")
		case "Asia/Aden":				 			self.init(identifier: "Asia/Riyadh")
		case "Asia/Ashkhabad": 		 				self.init(identifier: "Asia/Ashgabat")
		case "Asia/Bahrain":			 			self.init(identifier: "Asia/Qatar")
		case "Asia/Calcutta":			 			self.init(identifier: "Asia/Kolkata")
		case "Asia/Chongqing":				 		self.init(identifier: "Asia/Shanghai")
		case "Asia/Chungking":			 			self.init(identifier: "Asia/Shanghai")
		case "Asia/Dacca":			 				self.init(identifier: "Asia/Dhaka")
		case "Asia/Harbin":			 				self.init(identifier: "Asia/Shanghai")
		case "Asia/Istanbul":			 			self.init(identifier: "Europe/Istanbul")
		case "Asia/Kashgar":			 			self.init(identifier: "Asia/Urumqi")
		case "Asia/Katmandu":			 			self.init(identifier: "Asia/Kathmandu")
		case "Asia/Kuwait":			 				self.init(identifier: "Asia/Riyadh")
		case "Asia/Macao":			 				self.init(identifier: "Asia/Macau")
		case "Asia/Muscat":			 				self.init(identifier: "Asia/Dubai")
		case "Asia/Phnom_Penh":			 			self.init(identifier: "Asia/Bangkok")
		case "Asia/Rangoon":			 			self.init(identifier: "Asia/Yangon")
		case "Asia/Saigon":			 				self.init(identifier: "Asia/Ho_Chi_Minh")
		case "Asia/Tel_Aviv":			 			self.init(identifier: "Asia/Jerusalem")
		case "Asia/Thimbu":			 				self.init(identifier: "Asia/Thimphu")
		case "Asia/Ujung_Pandang":					self.init(identifier: "Asia/Makassar")
		case "Asia/Ulan_Bator":			 			self.init(identifier: "Asia/Ulaanbaatar")
		case "Asia/Urumqi":			 				self.init(identifier: "Asia/Shanghai")
		case "Asia/Vientiane":			 			self.init(identifier: "Asia/Bangkok")
		case "Atlantic/Faeroe":			 			self.init(identifier: "Atlantic/Faroe")
		case "Atlantic/Jan_Mayen":			 		self.init(identifier: "Europe/Oslo")
		case "Atlantic/St_Helena":				 	self.init(identifier: "Africa/Abidjan")
		case "Australia/ACT":			 			self.init(identifier: "Australia/Sydney")
		case "Australia/Canberra":			 		self.init(identifier: "Australia/Sydney")
		case "Australia/Currie":			 		self.init(identifier: "Australia/Hobart")
		case "Australia/LHI":			 			self.init(identifier: "Australia/Lord_Howe")
		case "Australia/North":			 			self.init(identifier: "Australia/Darwin")
		case "Australia/NSW":			 			self.init(identifier: "Australia/Sydney")
		case "Australia/Queensland":				self.init(identifier: "Australia/Brisbane")
		case "Australia/South":			 			self.init(identifier: "Australia/Adelaide")
		case "Australia/Tasmania":			 		self.init(identifier: "Australia/Hobart")
		case "Australia/Victoria":			 		self.init(identifier: "Australia/Melbourne")
		case "Australia/West":			 			self.init(identifier: "Australia/Perth")
		case "Australia/Yancowinna":			 	self.init(identifier: "Australia/Broken_Hill")
		case "Brazil/Acre":			 				self.init(identifier: "America/Rio_Branco")
		case "Brazil/DeNoronha":			 		self.init(identifier: "America/Noronha")
		case "Brazil/East":			 				self.init(identifier: "America/Sao_Paulo")
		case "Brazil/West":			 				self.init(identifier: "America/Manaus")
		case "Canada/Atlantic":			 			self.init(identifier: "America/Halifax")
		case "Canada/Central":			 			self.init(identifier: "America/Winnipeg")
		case "Canada/Eastern":			 			self.init(identifier: "America/Toronto")
		case "Canada/Mountain":			 			self.init(identifier: "America/Edmonton")
		case "Canada/Newfoundland":			 		self.init(identifier: "America/St_Johns")
		case "Canada/Pacific":			 			self.init(identifier: "America/Vancouver")
		case "Canada/Saskatchewan":			 		self.init(identifier: "America/Regina")
		case "Canada/Yukon":			 			self.init(identifier: "America/Whitehorse")
		case "CET":			 						self.init(identifier: "Europe/Paris")
		case "Chile/Continental":				 	self.init(identifier: "America/Santiago")
		case "Chile/EasterIsland":					self.init(identifier: "Pacific/Easter")
		case "CST6CDT":								self.init(identifier: "America/Chicago")
		case "Cuba":			 					self.init(identifier: "America/Havana")
		case "EET":			 						self.init(identifier: "Europe/Sofia")
		case "Egypt":			 					self.init(identifier: "Africa/Cairo")
		case "Eire":			 					self.init(identifier: "Europe/Dublin")
		case "EST":			 						self.init(identifier: "America/Cancun")
		case "EST5EDT":								self.init(identifier: "America/New_York")
		case "Etc/GMT":								self.init(identifier: "GMT")
		case "Etc/GMT+0":							self.init(identifier: "GMT")
		case "Etc/GMT+1":							self.init(identifier: "GMT+1")
		case "Etc/GMT+10":							self.init(identifier: "GMT+10")
		case "Etc/GMT+11":							self.init(identifier: "GMT+11")
		case "Etc/GMT+12":							self.init(identifier: "GMT+12")
		case "Etc/GMT+2":							self.init(identifier: "GMT+2")
		case "Etc/GMT+3":							self.init(identifier: "GMT+3")
		case "Etc/GMT+4":							self.init(identifier: "GMT+4")
		case "Etc/GMT+5":							self.init(identifier: "GMT+5")
		case "Etc/GMT+6":							self.init(identifier: "GMT+6")
		case "Etc/GMT+7":							self.init(identifier: "GMT+7")
		case "Etc/GMT+8":							self.init(identifier: "GMT+8")
		case "Etc/GMT+9":							self.init(identifier: "GMT+9")
		case "Etc/GMT-0":							self.init(identifier: "GMT")
		case "Etc/GMT-1":							self.init(identifier: "GMT-1")
		case "Etc/GMT-10":							self.init(identifier: "GMT-10")
		case "Etc/GMT-11":							self.init(identifier: "GMT-11")
		case "Etc/GMT-12":							self.init(identifier: "GMT-12")
		case "Etc/GMT-13":							self.init(identifier: "GMT-13")
		case "Etc/GMT-14":							self.init(identifier: "GMT-14")
		case "Etc/GMT-2":							self.init(identifier: "GMT-2")
		case "Etc/GMT-3":							self.init(identifier: "GMT-3")
		case "Etc/GMT-4":							self.init(identifier: "GMT-4")
		case "Etc/GMT-5":							self.init(identifier: "GMT-5")
		case "Etc/GMT-6":							self.init(identifier: "GMT-6")
		case "Etc/GMT-7":							self.init(identifier: "GMT-7")
		case "Etc/GMT-8":							self.init(identifier: "GMT-8")
		case "Etc/GMT-9":							self.init(identifier: "GMT-9")
		case "Etc/GMT0":	 						self.init(identifier: "GMT")
		case "Etc/Greenwich":	 					self.init(identifier: "GMT")
		case "Etc/Universal":	 					self.init(identifier: "UTC")
		case "Etc/Zulu":	 						self.init(identifier: "UTC")
		case "Europe/Belfast":			 			self.init(identifier: "Europe/London")
		case "Europe/Bratislava":					self.init(identifier: "Europe/Prague")
		case "Europe/Busingen":			 			self.init(identifier: "Europe/Zurich")
		case "Europe/Guernsey":			 			self.init(identifier: "Europe/London")
		case "Europe/Isle_of_Man":					self.init(identifier: "Europe/London")
		case "Europe/Jersey":			 			self.init(identifier: "Europe/London")
		case "Europe/Ljubljana":		 			self.init(identifier: "Europe/Belgrade")
		case "Europe/Mariehamn":					self.init(identifier: "Europe/Helsinki")
		case "Europe/Nicosia":			 			self.init(identifier: "Asia/Nicosia")
		case "Europe/Podgorica":					self.init(identifier: "Europe/Belgrade")
		case "Europe/San_Marino":					self.init(identifier: "Europe/Rome")
		case "Europe/Sarajevo":			 			self.init(identifier: "Europe/Belgrade")
		case "Europe/Skopje":			 			self.init(identifier: "Europe/Belgrade")
		case "Europe/Tiraspol":			 			self.init(identifier: "Europe/Chisinau")
		case "Europe/Vaduz":			 			self.init(identifier: "Europe/Zurich")
		case "Europe/Vatican":			 			self.init(identifier: "Europe/Rome")
		case "Europe/Zagreb":			 			self.init(identifier: "Europe/Belgrade")
		case "GB":			 						self.init(identifier: "Europe/London")
		case "GB-Eire":			 					self.init(identifier: "Europe/London")
		case "GMT+0":			 					self.init(identifier: "GMT")
		case "GMT-0":			 					self.init(identifier: "GMT")
		case "GMT0":			 					self.init(identifier: "GMT")
		case "Greenwich":			 				self.init(identifier: "GMT")
		case "Hongkong":				 			self.init(identifier: "Asia/Hong_Kong")
		case "HST":			 						self.init(identifier: "Pacific/Honolulu")
		case "Iceland":			 					self.init(identifier: "Atlantic/Reykjavik")
		case "Indian/Antananarivo":					self.init(identifier: "Africa/Nairobi")
		case "Indian/Comoro":						self.init(identifier: "Africa/Nairobi")
		case "Indian/Mayotte":						self.init(identifier: "Africa/Nairobi")
		case "Iran":								self.init(identifier: "Asia/Tehran")
		case "Israel":								self.init(identifier: "Asia/Jerusalem")
		case "Jamaica":								self.init(identifier: "America/Jamaica")
		case "Japan":								self.init(identifier: "Asia/Tokyo")
		case "Kwajalein":			 				self.init(identifier: "Pacific/Kwajalein")
		case "Libya":			 					self.init(identifier: "Africa/Tripoli")
		case "MET":			 						self.init(identifier: "Europe/Paris")
		case "Mexico/BajaNorte":					self.init(identifier: "America/Tijuana")
		case "Mexico/BajaSur":			 			self.init(identifier: "America/Mazatlan")
		case "Mexico/General":			 			self.init(identifier: "America/Mexico_City")
		case "MST":			 						self.init(identifier: "America/Phoenix")
		case "MST7MDT":			 					self.init(identifier: "America/Denver")
		case "Navajo":			 					self.init(identifier: "America/Denver")
		case "NZ":			 						self.init(identifier: "Pacific/Auckland")
		case "NZ-CHAT":			 					self.init(identifier: "Pacific/Chatham")
		case "Pacific/Johnston":					self.init(identifier: "Pacific/Honolulu")
		case "Pacific/Midway":			 			self.init(identifier: "Pacific/Pago_Pago")
		case "Pacific/Ponape":			 			self.init(identifier: "Pacific/Pohnpei")
		case "Pacific/Saipan":			 			self.init(identifier: "Pacific/Guam")
		case "Pacific/Samoa":			 			self.init(identifier: "Pacific/Pago_Pago")
		case "Pacific/Truk": 		 				self.init(identifier: "Pacific/Chuuk")
		case "Pacific/Yap":			 				self.init(identifier: "Pacific/Chuuk")
		case "Poland":			 					self.init(identifier: "Europe/Warsaw")
		case "Portugal":			 				self.init(identifier: "Europe/Lisbon")
		case "PRC":			 						self.init(identifier: "Asia/Shanghai")
		case "PST8PDT":			 					self.init(identifier: "America/Los_Angeles")
		case "ROC":			 						self.init(identifier: "Asia/Taipei")
		case "ROK":			 						self.init(identifier: "Asia/Seoul")
		case "Singapore":			 				self.init(identifier: "Asia/Singapore")
		case "Turkey":			 					self.init(identifier: "Europe/Istanbul")
		case "UCT":			 						self.init(identifier: "UTC")
		case "Universal":			 				self.init(identifier: "UTC")
		case "US/Alaska":			 				self.init(identifier: "America/Anchorage")
		case "US/Aleutian":			 				self.init(identifier: "America/Adak")
		case "US/Arizona":			 				self.init(identifier: "America/Phoenix")
		case "US/Central":							self.init(identifier: "America/Chicago")
		case "US/East-Indiana":						self.init(identifier: "America/Indiana/Indianapolis")
		case "US/Eastern":			 				self.init(identifier: "America/New_York")
		case "US/Hawaii":			 				self.init(identifier: "Pacific/Honolulu")
		case "US/Indiana-Starke":					self.init(identifier: "America/Indiana/Knox")
		case "US/Michigan":			 				self.init(identifier: "America/Detroit")
		case "US/Mountain":			 				self.init(identifier: "America/Denver")
		case "US/Pacific":			 				self.init(identifier: "America/Los_Angeles")
		case "US/Samoa":			 				self.init(identifier: "Pacific/Pago_Pago")
		case "W-SU":			 					self.init(identifier: "Europe/Moscow")
		case "WET":			 						self.init(identifier: "Europe/Lisbon")
		case "Zulu":			 					self.init(identifier: "UTC")
		default: 									self.init(identifier: name)
		}
	
	}

}

